name: НОВОЕ СОБЫТИЕ
description: Добавление в реестр нового события
title: "[NEW EVENT]: "
labels: ["new event"]
body:
  - type: input
    id: date
    attributes:
      label: Дата
      description: Дата начала события, формат YYYY-MM-DD
      placeholder: YYYY-MM-DD
    validations:
      required: true
  - type: input
    id: city
    attributes:
      label: Город
      description: Город, где будет проходить событие
      placeholder: Москва
    validations:
      required: true
  - type: input
    id: address
    attributes:
      label: Адрес проведения
      description: Адрес проведения мероприятия
      placeholder: ул. Арбат, 12
    validations:
      required: false
  - type: input
    id: icon
    attributes:
      label: Логотип
      description: Файл с логотипом (если нет то default.jpg)
      placeholder: default.jpg
    validations:
      required: false
  - type: input
    id: registration_url
    attributes:
      label: Ссылка на регистрацию
      description: Если нужны UTM метки, можно их добавить к ссылке
      placeholder: https://example.com/register
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Краткое описание события
      description: Краткое описание события, чтобы сразу понять, о чем оно.
      placeholder: 
    validations:
      required: true

